---
- hosts: all
  become: true
  become_user: "jtprogru"

  vars:
    full_name: "Michael Savin"
    ansible_distribution: ["Ubuntu", "Debian", "RHEL", "CentOS"]
    practice: ["DevOps", "IaC", "CI/CD/CD", "DaC"]
    ssh_public_key: https://github.com/jtprogru.keys
    instruments: ["Ansible", "SaltStack", "GitHub", "GitLab", "Bitrbucket", "Jira", "Trello", "Zabbix", "Prometheus", "Grafana",
                  "Confluence", "GiLab/GitHub Wiki", "Notion", "Proxmox", "VMware", "Docker", "LXC"]
    contacts:
      cv_ru: "https://savinmi.ru/"
      telegram: "@jtprogru"

  roles:
    - "{{ remote_user }}.infrastructure_engineer"
    - "{{ remote_user }}.linux_administrator"
    - "{{ remote_user }}.devops_engineer"

