---
- name: CV
  hosts: all
  become: true
  become_user: Michael Savin
  strategy: mitogen_linear

  vars:
    remote_user: "jtprogru"
    ansible_distribution: ["Ubuntu", "Debian", "RHEL", "CentOS"]
    practice: ["DevOps", "IaC", "CI/CD", "DaC"]
    instruments: 
      - configuration_managment: ["Ansible", "SaltStack"]
      - version_control: ["GitLab", "GitHub", "Bitrbucket"]
      - task_manager: ["Jira", "Trello"]
      - monitoring: ["Zabbix", "Prometheus", "Grafana"]
      - documentation: ["Confluence", "GiLab/GitHub Wiki", "Slite", "Notion"]
      - virtualisation: ["Proxmox", "VMware"]
      - orchestrator: ["Kubernetes", "Swarm"]
    contacts:
      site: "https://jtprog.ru"
      cv_ru: "https://jtprog.ru/resume/"
      cv_en: "https://jtprog.ru/resume-en/"
      email: "mail@jtprog.ru"
      telegram: "@jtprogru"
      twitter: "@jtprogru"

  roles:
    - "{{ remote_user }}.infrastructure_engineer"
    - "{{ remote_user }}.linux_administrator"
    - "{{ remote_user }}.devops_engineer"

